### ISSUE TITLE
add Content Negotation support

### ISSUE THREAD

**Issue by egonw** [wikipathways/WpVocabularies#11]
with:
- RDF/XML: application/rdf+xml
- Turtle: text/turtle

**Comment by nunogit** [comment]
This problem is solved.
The system now supports content negotiation with:
text/html
application/rdf+xml
text/turtle

**Comment by ariutta** [comment]
Could we also get JSON-LD?

**Comment by ariutta** [comment]
These ontologies are on BioPortal:

http://bioportal.bioontology.org/ontologies/GPML
http://bioportal.bioontology.org/ontologies/WIKIPATHWAYS
http://bioportal.bioontology.org/ontologies/MIM

I had been using this URL to allow the GPML vocab to be made accessible as RDF/XML:
http://rdf-translator.appspot.com/convert/rdfa/xml/http%3A%2F%2Fvocabularies.wikipathways.org%2Fgpml

Should I switch them to another URL now?

**Comment by egonw** [comment]
Yes, JSON-LD can be supported as well. Nuno, can you add that?

**Comment by egonw** [comment]
@nunogit, the MIME type for JSON-LD is application/ld+json ... the same service supports it as output format.

**Comment by egonw** [comment]
All implemented and up and running. HT @nunogit
