### ISSUE TITLE
Replacement of w3.org RDFa extractor

### ISSUE THREAD

**Issue by ariutta** [wikipathways/WpVocabularies#21]
It appears the w3.org RDFa extractor doesn’t work anymore:
https://www.w3.org/2012/pyRdfa/?uri=http://vocabularies.wikipathways.org/wp
BioPortal had been using that to keep our WikiPathways ontology up to date:
https://bioportal.bioontology.org/ontologies/WIKIPATHWAYS
Any ideas for a replacement solution, @egonw?

**Comment by AlexanderPico** [comment]
Maybe check with BioPortal to see if they are motivated to "fix" this for multiple sources that supply RDFa.

**Comment by egonw** [comment]
I used to have Bioclipse code to do this: https://www.myexperiment.org/workflows/921.html But it turns out this uses the online service. There is a Java library but this is unmaintained.

This is going to take a bit longer.

**Comment by egonw** [comment]
@ammar257ammar gave me a lead this morning: https://any23.apache.org/

**Comment by egonw** [comment]
Okay, I can now do this on the command line, see this blog post: https://chem-bla-ics.blogspot.com/2022/07/extracting-triples-from-htmlrdfa-pages.html

I will first upload the OWL files manually, but I'm considering wrapping this in a GitHub action for another project. Not sure if it makes sense here, as these vocabs don't change a lot.

**Comment by egonw** [comment]
I uploaded the OWL files and updated the HTML pages.
