### ISSUE TITLE
rdfs:range of wp:organism and wp:organismName need to be checked

### ISSUE THREAD

**Issue by egonw** [wikipathways/WpVocabularies#5]
They seem to have inverted ranges compared to each other, with respect to the current WPRDF.

**Comment by ariutta** [comment]
Is one of these supposed to be just a string, e.g., "Homo sapiens" and the other a resource, e.g., http://identifiers.org/taxonomy/9606 ?

Also, what is the relationship between organism in the WP vocab and in the [BridgeDb vocab](http://vocabularies.bridgedb.org/ops#)?

In bridgedbjs, I use [snomedct:Organism](https://bridgedb.github.io/bridgedbjs/docs/global.html#Organism) for the class and biopax:organism for the property. For the class, I handle Latin and English names using [language maps](http://www.w3.org/TR/json-ld/#language-maps).
