### ISSUE TITLE
can wp:Protein subclass wp:GeneProduct ?

### ISSUE THREAD

**Issue by egonw** [wikipathways/WpVocabularies#6]

**Comment by ariutta** [comment]
I would subclass wp:Protein and wp:Rna under wp:GeneProduct, but I'd like to get confirmation from @AlexanderPico and @mkutmon.

**Comment by mkutmon** [comment]
Hmm good question. I think GeneProduct as a superclass for Protein and RNA should be fine. Although we don't really use it like that in GPML or pathways, I guess semantically that should be correct.

**Comment by Chris-Evelo** [comment]
Agree

**Comment by AlexanderPico** [comment]
I agree.
